### ISSUE TITLE
Can't create or update object

### ISSUE THREAD

**Issue by quevon24** [Tivix/django-cron#105]
Hi, I was wondering if it's possible to create or update an object inside a cron job function? Because I tried but without success. The execution stops at the create() or update() line without any error. It's possible to update an object using save() but not to create it. Thanks.

**Comment by sci-tab** [comment]
@quevon24 I need more information. The quick answer based on what I can understand is yes. Can you post your cron job, describe exactly what you are trying to create, and any errors you get?  Thanks!

**Comment by AnthonyJCalabro** [comment]
Im also coming across a similar issue.

Im running Django with a postgresql database and for some reason cron tasks will stop execution as soon as I attempt to update a model.

**Comment by maxim-kht** [comment]
Hi @AnthonyJCalabro could you please paste the message from CronJobLog? It can be retrieved in admin or Django shell.

**Comment by AnthonyJCalabro** [comment]
Hi @maxim-kht thankyou for the quick reply.

I checked the message and the error was a mistake on my end.

I was using:

`datetime.now()`

Instead of 
`datetime.datetime.now()`

Thankyou for the help regardless
