### ISSUE TITLE
Add dry-run functionality to aid development

### ISSUE THREAD

**Issue by evenicoulddoit** [Tivix/django-cron#106]
Whilst integration Django Cron into our project, I wanted to ensure that it would run as expected.
In order to make that easier, I suggest we add a `--dry-run` flag which, in addition to slightly improved output from the management command, should make it easier to see what *will* happen, before actually running anything.

See #102

**Comment by sci-tab** [comment]
@evenicoulddoit I like this addition and we will review it shortly. Thanks! 👍

**Comment by JedrzejMaluszczak** [comment]
#102
