### ISSUE TITLE
Warning still needed?

### ISSUE THREAD

**Issue by guettli** [Tivix/django-cron#120]
Thank you for django-cron and sharing it.

Do you think this warning is still needed today? I guess most people switched from south to a more modern solution today.

{{{
WARNING

When upgrading from 0.3.6 to later versions you might need to remove existing South migrations, read more: https://docs.djangoproject.com/en/1.7/topics/migrations/#upgrading-from-south

}}}

**Comment by maxim-kht** [comment]
Hi @guettli

It’s a good point, the warning is not really necessary now, since migrations have been included natively in Django for a long time. We will remove the warning with next release.
