### ISSUE TITLE
Do you recommend celery?

### ISSUE THREAD

**Issue by guettli** [Tivix/django-cron#121]
You reference celery in the README.

Can you recommend it?

I tried it several months ago and it was too big and too complicated.

I am curious what you think about it.

Have you hear of https://channels.readthedocs.io/en/stable/ ?

BTW, I  hope it is all right that I ask you questions via github issues. If not, please tell me :-)

**Comment by maxim-kht** [comment]
Hi @guettli

It really depends on what functionality you require for your application. Celery is very nice and efficient tool if you need to offload certain tasks or run things asynchronously in Python application. I would suggest reading some blog posts about integrating Celery with Django, as they usually also define some of the use cases for it.

We are also familiar with Django channels, although it’s a newer technology, and it’s not used in production a lot yet. I would recommend this blog post about it https://blog.heroku.com/in_deep_with_django_channels_the_future_of_real_time_apps_in_django
