### ISSUE TITLE
Error saving cronjob log message

### ISSUE THREAD

**Issue by parker45** [Tivix/django-cron#124]
I am getting the following error: 

"Error saving cronjob log message: relation "django_cron_cronjoblog" does not exist LINE 1: INSERT INTO "django_cron_cronjoblog" ("code", "start_time", ..."

 after running manage.py runcrons --forced 
I cant seem to find out what is causing the error.

**Comment by maxim-kht** [comment]
Hi @parker45 did you run the migration command after including the app? `python manage.py migrate django_cron`

**Comment by parker45** [comment]
That did it for me thanks!!
