### ISSUE TITLE
Doesn't run task

### ISSUE THREAD

**Issue by brayan15** [Tivix/django-cron#125]
I defined my task, but doesn't want show, I added a simple code:
class MyCronJob(CronJobBase):
    RUN_EVERY_MINS = 1 # every 2 hours

    schedule = Schedule(run_every_mins=RUN_EVERY_MINS)
    #code = 'my_app.my_cron_job'    # a unique code

    def do(self):
        print('aaa')

and on setting I putted this:
CRON_CLASSES = [
    "vehicle_control_system.persons.contrab.MyCronJob",
    # ...
]

and later I run django with python manage.py runserver, but never isn't showing

**Comment by FrankMeyer** [comment]
Hi brayan,

the crons are not executed with the debug-server. They are executed by the command runcrons.
Usually you call manage.py runcrons from your crontab every minute.
For example:
*/1 * * * * www-data python /var/www/project/manage.py runcrons > /var/www/project/log/cronjobs.log

**Comment by brayan15** [comment]
Ohh I see, but I can run server and crons with this command (manage.py runcrons)??

**Comment by FrankMeyer** [comment]
No, manage.py runcrons is for running the cron jobs only.
This app has nothing to do with the django developement server.
You still run manage.py runserver from the command line.
