### ISSUE TITLE
getting /bin/sh: 1: source: not found

### ISSUE THREAD

**Issue by KaiserKarel** [Tivix/django-cron#129]
Followed the documentation, but getting /bin/sh: 1: source: not found in my cronjob.log file. Crons are working fine if I manually run manage.py runcrons --force

my crontab:
*/5 * * * *  (source /home/<user>/.bashrc && source /home/<user>/venv/bin/activate && python /home/<user>/myapp/manage.py runcrons) > /home/<user>/cronjob.log 2>&1

**Comment by AbeIgnocious** [comment]
For those in the same predicament, I found the fix 5 minutes after posting this.

https://stackoverflow.com/questions/3287038/cron-and-virtualenv

adding SHELL=/bin/bash did fix my issue
