### ISSUE TITLE
Set user_time for RUN_AT_TIMES

### ISSUE THREAD

**Issue by tatulea** [Tivix/django-cron#134]
Hi,

I think it would be nice to set user_time to cron_job_class be allow user to check the time for which the cron will run.

I did it just adding:
```
setattr(self.cron_job_class, 'user_time', time_data)
```
on 147 line from __init__.py.

Could you put it in thr project also, please?

Thank you!

**Comment by organism** [comment]
Do you mean to limit the amount of time the cron is allowed to run?

**Comment by tatulea** [comment]
No, to be able to access in self the time that the cron was set to run. I had a cron and I needed to know the time that it was intended to run at
