### ISSUE TITLE
Cache backend locking - error with failure at redis (probably) replication.

### ISSUE THREAD

**Issue by kregoslup** [Tivix/django-cron#136]
Suppose we have Redis with a master-slave replication and we are using redis as backend for locking. Because redis does not support consistency out of the box there is no guarantee that here https://github.com/Tivix/django-cron/blob/master/django_cron/backends/lock/cache.py#L89 

```
def get_running_lock_date(self):
        date = self.cache.get(self.lock_name)  # <---
        if not timezone.is_aware(date):
            tz = timezone.get_current_timezone()
            date = timezone.make_aware(date, tz)
        return date
```

the date that was taken from cache will be in a format suitable for datetime parser. What do you think about that?

**Comment by agronick** [comment]
Every day I'm getting failed crons with this issue. I guess the crons finish up between the first and second check.

**Comment by agronick** [comment]
Theres 11 unmerged merge requests. Last change was a year ago. I think this project as abandoned.

**Comment by PawelMorawian** [comment]
Is someone willing to take it over ?

**Comment by kregoslup** [comment]
Resolved here: https://github.com/Tivix/django-cron/pull/130/files
