### ISSUE TITLE
Project is abandoned

### ISSUE THREAD

**Issue by agronick** [Tivix/django-cron#138]
Open bugs, pull requests that haven't been looked at in over a year. Probably should not use this in production and move away from it if you are.

**Comment by maxim-kht** [comment]
Hi @agronick, thank you for your concern. This project currently has no critical bugs and is tested with latest Django version and it is suitable for production. The main issue we had before, with timezone.aware() method, was not critical and did not cause problems with running cron jobs.

The latest version 0.5.1 fixes it and some of the other bugs we had. You can find more information about the release here: https://github.com/Tivix/django-cron/releases/tag/v0.5.1

**Comment by agronick** [comment]
It did have critical bugs. It would crash when cache keys weren't present. Thank you for finally addressing this.
