### ISSUE TITLE
Run weekly

### ISSUE THREAD

**Issue by matburnham** [Tivix/django-cron#151]
I'm trying to run a backup task once a week. The following runs a daily backup, but the weekly doesn't seem to happen. It's rather difficult to debug as I only want it to happen once a week!

```
class Backup(CronJobBase):
    RUN_AT_TIMES = ['23:00']
    schedule = Schedule(run_at_times=RUN_AT_TIMES)
    code = 'mysite.Backup'

    def do(self):
        management.call_command('dbbackup')

class BackupImages(CronJobBase):
    # Backup once a week
    RUN_EVERY_MINS = 60 * 24 * 7
    schedule = Schedule(run_every_mins=RUN_EVERY_MINS)
    code = 'mysite.BackupImages'

    def do(self):
      management.call_command('mediabackup', '--compress')
```

Is running less often than daily supported? Is there a better way to do this?

**Comment by gregschmit** [comment]
I don't know whether this is supported, however, as a workaround, you could give your model a day to run on (0-6, Mon-Sun), and then run your CronJob daily and in your management command check to see if it is the right day using `timezone.localtime(timezone.now()).weekday()`.

**Comment by matburnham** [comment]
Sounds like a good workaround @gregschmit. Thanks.

**Comment by eagle-r** [comment]
We have done something similar for running jobs monthly

**Comment by JedrzejMaluszczak** [comment]
Take a look at Run weekly feature:
https://github.com/Tivix/django-cron/blob/master/docs/sample_cron_configurations.rst
