### ISSUE TITLE
`django.utils.translation.ugettext_lazy` is deprecated and will be removed in 4.0

### ISSUE THREAD

**Issue by tiholic** [Tivix/django-cron#174]
```
<project-venv>/lib/python3.8/site-packages/django_cron/admin.py:12: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
  title = _('duration')
```

**Comment by rehmatworks** [comment]
Looks like the author isn't active. I have forked this repo, has made the changes and I have published it at PyPi. It can be installed as:

```bash
pip install django4-cron
```

Just those imports have been fixed and the rest is the same. You need to follow the exact same  (official) documentation to get this to work.

**Comment by rehmatworks** [comment]
#186
