### ISSUE TITLE
Wrong depreciation message in README

### ISSUE THREAD

**Issue by PawelMorawian** [Tivix/django-cron#177]
Hello,

Yesterday a depreciation message has been added to the README by @chachra .

https://github.com/Tivix/django-cron/blob/master/README.rst#deprecated

It is wrong, the package `dj-rest-auth` has nothing to do with this one.

**Comment by weslord** [comment]
Clearly meant for https://github.com/Tivix/django-rest-auth/ (see https://github.com/Tivix/django-rest-auth/issues/568).

I've created a PR in the django-rest-auth repo with a copy of the wording from this one, and created a PR here (#189) removing the link.

**Comment by T4m** [comment]
Do you have any suggestion to actually replace this deprecated package ?
