### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by drego** [Tivix/django-cron#19]
Hi,
i do everything like readme file.
Right now i can do python manage.py runcrons and it works.

my cron job looks like this:

class MyCronJob(CronJobBase):
    RUN_EVERY_MINS = 1 # mins
    MIN_NUM_FAILURES = 3

```
schedule = Schedule(run_every_mins=RUN_EVERY_MINS)
code = 'my_app.my_cron_job'    # a unique code

def do(self):
    print "pass"
```

So, it prints "pass" when i type "python manage.py runcrons"
But when i run server with "python manage.py runserver", server runs but no string shown in console...
Can you help me? Thanks in advance!

**Comment by xporium** [comment]
crontab is not working in windows so any other option to autorun service.... 
also dont want to create manually windows task scheduler from control panel so please tell me other option for that.
