### ISSUE TITLE
Maintained or not maintained - that's the question.

### ISSUE THREAD

**Issue by knobix** [Tivix/django-cron#198]
Hi,

it seems that this project is being maintained again after some time of hiatus because 0.6.0 was recently released.

But if one looks at the `README.rst` there's still the note that the project is unmaintained.  The same applies if one looks at the entry of `django-cron` at PyPI.

If this project is maintained then it would make sense to update the `README.rst`.

**Comment by JedrzejMaluszczak** [comment]
I am resuming work on this project. I will update the README, I just forgot about it
