### ISSUE TITLE
runcrons is once-and-for-all?

### ISSUE THREAD

**Issue by hunanboy** [Tivix/django-cron#21]
The following cron job class is intended to send email every min once running "runcrons" command. But in fact, it only sends out one email every time I run runcrons command (instead of send one email per minute). That defeats the purpose of cron... Am I missing something?

class TestCron(CronJobBase):
    schedule = Schedule(run_every_mins=1)
    code = 'test_cron_philip'

```
def do(self):
    send_mail('cron test', 'body is test body', 'coach_zhong@163.com',
              ['admin@dessert.webfactional.com'],fail_silently=False)
```

**Comment by DanielStevenLewis** [comment]
I also experienced this issue until finding this ticket. Documentation could use further clarification. "everytime you run the management command python manage.py runcrons all the crons will run if required." indicates to me that manage.py runcrons starts a recurring cron job

**Comment by craiglabenz** [comment]
Link to the SO question?

**Comment by shivamsinghal212** [comment]
I don't understand the point of setting schedule in django-cron, If we are setting it using the windows task scheduler.

**Comment by craiglabenz** [comment]
@shivamsinghal212 The idea is that your window task scheduler will invoke `python manage.py runcrons` very regularly -- say, every minute, or every 5 minutes. `django-cron` then internally maintains the schedule of your jobs, launching each as necessary. This allows you to easily keep said schedules inside your application code and thus inside version control.
