### ISSUE TITLE
Django 1.7 ImportError on runcrons.py management command

### ISSUE THREAD

**Issue by Clean-Cole** [Tivix/django-cron#35]
On Django 1.7 running github master branch install of django-cron

When trying to run ```python manage.py runcrons``` I received an import error on..
```
from django.db import close_connection
```

**Comment by tiagoboldt** [comment]
Same: /Users/tiagoboldt/home/work/labprot-local-adaptor/venv/lib/python2.7/site-packages/django_cron/management/commands/runcrons.py:41: RemovedInDjango18Warning: close_connection is superseded by close_old_connections.

Could this fix be shipped to the repository?

**Comment by dfryta** [comment]
Done. Thanks!

**Comment by selva** [comment]
i unable use django cron i dont know why, can some one help me, how to resolve this,

my problem is 
home/selva/hysovirtual/local/lib/python2.7/site-packages/django/core/management/__init__.py:345: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  self.fetch_command(subcommand).run_from_argv(self.argv)

**Comment by craiglabenz** [comment]
What version of Django, @selva? Looks like probably `1.9` based on that warning.

**Comment by craiglabenz** [comment]
Looks like a dupe of #84
