### ISSUE TITLE
Django 1.7 compatibility

### ISSUE THREAD

**Issue by ataz** [Tivix/django-cron#43]
When trying to migrate django_cron in a project with Django 1.7, the following error is raised:
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: django_cron

Due to the changes in Django 1.7 requiring apps to have a unique label. https://docs.djangoproject.com/en/1.7/ref/applications/#for-application-authors

**Comment by gkadillak** [comment]
I'm running into the same issue.

**Comment by mjaworski** [comment]
Did you name your own app django_cron? The solution then is to simply rename your app.

**Comment by ataz** [comment]
@mjaworski That is not the issue; the problem lies with the package itself. It's really easy to reproduce, just try to use this lib in a Django 1.7 env and it won't work :-)

For me the "solution" was to use https://github.com/kraiz/django-crontab instead.

**Comment by mjaworski** [comment]
@ataz just did, added django_cron to INSTALLED_APPS, ran migrations and everything worked fine

**Comment by ataz** [comment]
Ok then I'm not sure what it is. I know that for me at least the problem wasn't that my app was named django_cron... This was 3 months ago though, so I don't remember the details. Perhaps @gkadillak can provide more details regarding the issue?

**Comment by mjaworski** [comment]
0.4.0 has been pushed, it's been tested on both 1.7 and 1.8
