### ISSUE TITLE
Django 1.8 Compatibility 

### ISSUE THREAD

**Issue by bartmika** [Tivix/django-cron#50]
Hi,

The documents says this only supports up until 1.7. Can you update the documents and or fix this package to support Django 1.8?

**Comment by mjaworski** [comment]
It's already fixed, new release should be pushed to PyPi by the end of the week.

**Comment by pidupuis** [comment]
Which version can I install with pip to use django-cron with Django 1.8 ?

**Comment by mjaworski** [comment]
0.4.0 has now been pushed to pypi, note that South has been dropped in favor of native Django migrations, this might require some action when upgrading from older versions
