### ISSUE TITLE
No handlers could be found for logger "django_cron"

### ISSUE THREAD

**Issue by jadelaop** [Tivix/django-cron#58]
In django 1.8 and debug=False:

python manage.py runcrons 
No handlers could be found for logger "django_cron"

**Comment by mjaworski** [comment]
Can you provide some more information, I cannot reproduce this error.

**Comment by chachra** [comment]
@mjaworski https://docs.python.org/3.1/library/logging.html#configuring-logging-for-a-library ?

**Comment by gungorbudak** [comment]
@jadelaop 

I solved this issue by adding following to `settings.py`:

```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/home/user/www/logs/django.log',
            },
        },
    'loggers': {
        'django_cron': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
```

Based on a comment here: http://stackoverflow.com/a/28780536/1597907

**Comment by chachra** [comment]
Thanks @gungorbudak for responding. Appreciate it.

**Comment by koharpardeep** [comment]
Run 'python manage.py makemigrations django_cron',''python manage.py migrate django_cron and 'python manage.py syncdb'.

**Comment by VamsidharMuggulla** [comment]
I use Google appengine's dev_server to run which cannot access the file system in any way what can I do for this.
