### ISSUE TITLE
In doubt

### ISSUE THREAD

**Issue by marcussaad** [Tivix/django-cron#60]
First of all, thanks for this app/project, it will be really helpful to me.

One thing that is making me confused is the fact that I'm able to define ```run_every_min``` or ```run_at``` and later at the docs it says that I'll need to setup a cronjob for it. 

So, defining those values works only like an if? In case I set it to ```run_every_min``` to 60, and set my cronjob to run every 60 minutes as well, what will that parameter do ?

**Comment by craiglabenz** [comment]
I would set your cron job to run every minute. It should only invoke the `django-cron` management command (`./manage.py runcrons`, if memory serves). Once that command starts, it will honor your `run_every_min` or `run_at` configuration by comparing the current time against the last known job runtime.

**Comment by mjaworski** [comment]
As mentioned above, runcrons should be set to run fairly frequently (docs recommend 5 minutes), the command itself will check if any of cronjobs you defined need to be run.

See relevant section of docs here:
http://django-cron.readthedocs.org/en/latest/installation.html

**Comment by marcussaad** [comment]
@craiglabenz and @mjaworski, thanks for those clarifications.
