### ISSUE TITLE
Error in file locking backend with python 3

### ISSUE THREAD

**Issue by Maberi** [Tivix/django-cron#74]
File ".../lib/python3.4/site-packages/django_cron/backends/lock/file.py", line 20, in lock
     f = open(lock_name, 'w+', 0)
 ValueError: can't have unbuffered text I/O

For python3, should change line 20 to f = open(lock_name, 'wb+', 0) and line 37 to  f.write(bytearray(str(os.getpid()), 'utf-8'))

**Comment by Mikuz** [comment]
I did the same except I changed the line 37 to:
f.write(bytes(str(os.getpid()), 'UTF-8'))

Tested and works.

**Comment by maxim-kht** [comment]
Resolved in https://github.com/Tivix/django-cron/pull/110
