### ISSUE TITLE
Is it possible to "log"/write to the "Messages" field of the cron log entries?

### ISSUE THREAD

**Issue by gtalarico** [Tivix/django-cron#81]
The field is populated with errors/traceback.
I would like to be able to log some messages, so that when it's successful I can see some of the data/results as well.
![image](https://cloud.githubusercontent.com/assets/9513968/13922845/86c170d0-ef54-11e5-914f-0a349f530c34.png)

**Comment by gtalarico** [comment]
I guess you could do it by just instantiating it's logger:
logger = logging.getLogger('django_cron')
May this could be included in the Docs?

**Comment by ihoru** [comment]
There is an easier way to do what you want:
just return string from do method in your Cron class.

**Comment by agronick** [comment]
The problem is that after a certain number of lines it gets cut off.

**Comment by eagle-r** [comment]
@agronick Its not a certain number of lines. For some reason messages are truncated to 1000 characters even though the model uses a TextField

**Comment by agronick** [comment]
You can see in the code where it truncates it.

**Comment by JedrzejMaluszczak** [comment]
as mentioned above: just return a string from do method in your Cron class.
