### ISSUE TITLE
Can't run the task at second time

### ISSUE THREAD

**Issue by mymusise** [Tivix/django-cron#82]
Hello,I found a  problem ,when i run the command `python manage.py runcrons` ,my task just run one time and wouldn't run anymore.
Here is My code:
##### mobile/cron.py

<pre>
class SimpleTaskCronJob(CronJobBase):
    RUN_EVERY_MINS = 1    

    schedule = Schedule(run_every_mins=RUN_EVERY_MINS)
    code = 'mobile.cron.SimpleTaskCronJob'

    def do(self):
        print "runing the task "
        msg = "I have done task in %s sec: %s"
</pre>

##### settings.py

<pre>
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cron',
    'mobile',
)

CRON_CLASSES = [
    "mobile.cron.SimpleTaskCronJob",
]
</pre>

is there any problem with my code??

**Comment by FrankMeyer** [comment]
You can add that command to your crontab, there you specify how often it should run.
See point 6 here: http://django-cron.readthedocs.org/en/latest/installation.html
