### ISSUE TITLE
Failed Cron task continuously running if task is failed

### ISSUE THREAD

**Issue by omprakashpatel** [Tivix/django-cron#87]
There is no configuration for stopping task if it fails for a fixed number of times.
Currently if my task is failing it will run again and again until it success.
there should be a config setting for "Max num of failures" to stop that.

there is one '**MIN_NUM_FAILURES**' attribute to set for email notification but this does not stops task!

**Comment by sci-tab** [comment]
#107 also addresses this and other problems with handling cron failures. Closing this as a duplicate for now. We will focus on that PR.
