### ISSUE TITLE
Not able to configure cron to run every minute

### ISSUE THREAD

**Issue by akashpatni** [Tivix/django-cron#91]
Hi,

I have used django-cron for setting up cron task for my project and I am able to run the scripts manually with command python manage.py runcrons and it is running for only one time. Now I want to run script for every minute and for that I have to use crontab -e and I have done in the same way as told in documentation but with no success.
- \* \* \* \* source /home/ubuntu/.bashrc && /usr/bin/python && source /home/aakash/Project/project-name/src/api/bin/activate && python /home/aakash/Project/project-name/src/manage.py runcrons > /home/aakash/Project/cronjob.log

Can you please help me on that

**Comment by somacci** [comment]
I have exactly same problem. If anyone can solutions. Please let me know it.

**Comment by ihoru** [comment]
This will make your task execute every time you call manage.py runcrons:
```python
schedule = Schedule(run_every_mins=0)
```
And if you want it to be executed every minute put 1 instead of 0.

**Comment by renzop** [comment]
Same Issue here... Running runcron every minute but this code gets executed every hour.

`
class ProveThatCronIsRunning(CronJobBase):
    schedule = Schedule(run_every_mins=2)
    code = 'ProveThatCronIsRunning'

    def do(self):
        logger.log('ProveThatDjangoCronIsRunning')

`

**Comment by Lapeth** [comment]
Setting run_every_mins=1 is error-prone: Consider that the crontab has us run every minute. If there is a slight difference in time offset on each run, the job might not be executed. Say the crontab executes at 08:00:00.02 and then at 08:01:00.01; there is less than a full minute between these timestamps, so django-cron passes on letting the job execute.

**Comment by sci-tab** [comment]
@akashpatni see [documentation](http://django-cron.readthedocs.io/en/latest/installation.html): 

> 6. Now everytime you run the management command python manage.py runcrons all the crons will run if required. Depending on the application the management command can be called from the Unix crontab as often as required. Every 5 minutes usually works for most of my applications, for example:

This is intended functionality

**Comment by sankethsj** [comment]
having the same issue. When I write "python manage.py runcrons", it works well for first time. But it wont run every minute. Help!

**Comment by JedrzejMaluszczak** [comment]
@sankethsj use `python manage.py cronloop` instead.
You need to update django-cron to version 0.6.0
